// <auto-generated />
using System;
using ElParqueito;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElParqueito.Migrations
{
    [DbContext(typeof(CadenaDeParqueosContext))]
    partial class CadenaDeParqueosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ElParqueito.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contrasenna")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("ElParqueito.Models.Estacionamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cobro")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraDeEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraDeSalida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numeroPosicion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("vehiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("vehiculoId");

                    b.ToTable("Estacionamientos");
                });

            modelBuilder.Entity("ElParqueito.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<int?>("estacionamientoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("estacionamientoId");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ElParqueito.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ElParqueito.Models.Estacionamiento", b =>
                {
                    b.HasOne("ElParqueito.Models.Vehiculo", "vehiculo")
                        .WithMany()
                        .HasForeignKey("vehiculoId");

                    b.Navigation("vehiculo");
                });

            modelBuilder.Entity("ElParqueito.Models.Factura", b =>
                {
                    b.HasOne("ElParqueito.Models.Estacionamiento", "estacionamiento")
                        .WithMany()
                        .HasForeignKey("estacionamientoId");

                    b.Navigation("estacionamiento");
                });
#pragma warning restore 612, 618
        }
    }
}
